from pathlib import Path
import csv
import json
import urllib.request
import re
import html

CSV_URL = "https://docs.google.com/spreadsheets/d/1KSzoIkOsjUagNBLt3IbKIvgWEmez4f0XISQ-jkUjmwQ/gviz/tq?tqx=out:csv&sheet=%E3%81%8A%E3%81%99%E3%81%99%E3%82%81Podcast"

# This URL is intentionally configurable via the published sheet. The sync job
# produces a last-known-good snapshot; it never replaces a healthy snapshot
# with an empty/obviously incomplete response.
with urllib.request.urlopen(CSV_URL, timeout=30) as response:
    table = list(csv.reader(response.read().decode("utf-8-sig").splitlines()))

if not table:
    raise SystemExit("停止：おすすめPodcastの公開CSVが空です")

header = [str(x).strip() for x in table[0]]
aliases = {
    "url": ["URL", "番組URL", "Podcast URL"],
    "title": ["番組名", "タイトル"],
    "maker": ["おすすめした人", "おすすめ朝リス", "朝リスネーム", "投稿者", "制作者"],
}
def col(names):
    for name in names:
        if name in header:
            return header.index(name)
    return None

title_col = col(aliases["title"])
url_col = col(aliases["url"])
maker_col = col(aliases["maker"])
if title_col is None or url_col is None or maker_col is None:
    raise SystemExit("停止：おすすめPodcast公開CSVの見出しが想定外です")

def value(row, names):
    i = col(names)
    return str(row[i]).strip() if i is not None and i < len(row) else ""

def apple_genre(apple_url):
    """Best-effort Apple Podcasts genre lookup. Never erase a sheet genre on failure."""
    if not apple_url or "podcasts.apple.com" not in apple_url:
        return ""
    try:
        request = urllib.request.Request(
            apple_url,
            headers={"User-Agent": "Mozilla/5.0 asarisunowa-recommended-sync/1.0"},
        )
        with urllib.request.urlopen(request, timeout=20) as response:
            page = response.read().decode("utf-8", errors="ignore")
        # Apple pages expose the visible category in breadcrumb/metadata links.
        candidates = re.findall(
            r'<a[^>]+href="[^"]*/genre/[^"]+"[^>]*>(.*?)</a>',
            page,
            re.I | re.S,
        )
        for candidate in candidates:
            genre = re.sub(r"<[^>]+>", "", candidate)
            genre = html.unescape(genre).strip()
            if genre and genre not in {"Podcast", "ポッドキャスト"}:
                return genre
    except Exception as error:
        print(f"注意：Apple Podcastsジャンルを取得できませんでした: {apple_url} ({error})")
    return ""

items = []
for source in table[1:]:
    title = value(source, aliases["title"])
    url = value(source, aliases["url"])
    maker = value(source, aliases["maker"])
    if not title:
        continue
    apple_url = value(source, ["Apple Podcasts", "Apple"])
    sheet_genre = value(source, ["genre", "ジャンル"])
    genre = apple_genre(apple_url) or sheet_genre or "その他"
    items.append({
        "id": str(len(items) + 1),
        "url": url,
        "title": title,
        "maker": maker,
        "comment": value(source, ["コメント", "ひとこと"]),
        "artwork": value(source, ["artwork", "アートワーク", "画像"]),
        "host": value(source, ["host", "配信者 / Host", "出演者"]),
        "genre": genre,
        "youtube": value(source, ["YouTube"]),
        "spotify": value(source, ["Spotify"]),
        "amazon": value(source, ["Amazon Music", "Amazon"]),
        "apple": apple_url,
        "pocketcasts": value(source, ["Pocket Casts"]),
        "listen": value(source, ["LISTEN"]),
        "standfm": value(source, ["stand.fm"]),
        "pody": value(source, ["Pody"]),
    })

target = Path("app/recommended-podcasts-data.ts")
if not items:
    raise SystemExit("停止：おすすめPodcastが0件のため正常スナップショットを保持します")

output = (
    "// AUTO-GENERATED by scripts/sync-recommended-podcasts.py\n"
    "export const recommendedPodcastSnapshot = "
    + json.dumps(items, ensure_ascii=False, indent=2)
    + " as const;\n"
)
target.write_text(output, encoding="utf-8")
print(f"成功：おすすめPodcast {len(items)}件を公開スナップショット化しました")
