const assert = require('node:assert/strict');
const {buildAutoUpdateDiagnosisSnapshotV1: build} = require('./AutoUpdateSnapshotAdapter');
const {diagnoseAutoUpdateEpisodeSnapshotV1: diagnose} = require('./AutoUpdateReadOnlyDiagnosis');
const sample = {states:[{candidateIds:['a','b']},{candidateIds:['b','c']}],playlistItems:[{item:{uri:'spotify:episode:a'}}],batchIds:['b','c'],spotifyResponse:{httpStatus:200,episodes:[{id:'b',is_playable:true},null,{id:'c',is_playable:false}]}};
const snapshot = build(sample);
assert.deepEqual(snapshot.candidateIds,['a','b','c']);
assert.deepEqual(snapshot.existingIds,['a']);
assert.deepEqual(diagnose(snapshot).unplayableIds,['c']);
assert.deepEqual(diagnose(build({...sample,spotifyResponse:{httpStatus:429}})).apiErrorIds,['b','c']);
assert.throws(()=>build({...sample,spotifyResponse:{httpStatus:200}}),/episodes array/);
assert.throws(()=>build({...sample,states:[{}]}),/candidateIds/);
assert.throws(()=>build({...sample,batchIds:['unknown']}) && diagnose(build({...sample,batchIds:['unknown']})),/subset/);
console.log('PASS: 7 offline adapter tests; no external services contacted');
